version: '2'
services:
  nginx:
     pid: "host"
     container_name: nginx #docker镜像名称
     restart: always #设置自启动
     #build: ./nginx #构建docker的Dockerfile目录
     image: luwenbin8023/nginx:1.8.1-alpine #本地镜像
     expose:
       - "80"
     ports:
       - "80:80" #宿主端口（映射到）-》docker镜像端口
       - "443:443" #宿主端口（映射到）-》docker镜像端口
     volumes:
       - ../www:/data/www:rw #站点根目录
       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro #nginx配置
       - ./nginx/sites-enabled:/etc/nginx/sites-enabled:rw #站点配置
       - ./nginx/fastcgi_params:/etc/nginx/fastcgi_params:ro #fastcgi配置
       #- ./nginx/fastcgi-php.conf::/etc/nginx/fastcgi-php.conf:ro
       - ./nginx/certs:/etc/nginx/certs #ssl证书
       - ./nginx/logrotate.d:/etc/logrotate.d/ # 日志分割配置
       - ./log/nginx:/data/log:rw #nginx log目录
     links:
       - "php56"  #连接其他docker镜像
       - "php72"
       - "php74"
       - "mysql56"
       - "mysql57"
       - "redis"
#     external_links:
#       - "graylog"
     privileged: true #设定读写权限
  php56:
      container_name: php56
      restart: always #设置自启动
      image: luwenbin8023/php:5.6-fpm-alpine3.8 #本地镜像
      volumes:
        - ../www:/data/www #站点根目录
        #- /php56/php.ini:/usr/local/etc/php/php.ini:ro
        - ./log/php:/opt/log/php #php log目录
        ##- ./dev.ini:/usr/local/etc/php/conf.d/safety.ini
      ports:
        - "9501:9501" #宿主端口（映射到）-》docker镜像端口
        - "9502:9502" #宿主端口（映射到）-》docker镜像端口
      privileged: true #设定读写权限
      environment:
        - SW_WORKER_NUM=10
        - SW_MAX_CONN=100
        - SW_TASK_NUM=5
        - GELF_TOKEN=ort75mte218kafjqeoqg3iqqb2r4uu8dq4bcgjm52r891f8m9tl
        - SITE_DEBUG=1
        - SERVER_ID=1
        - DAEMON=0
      #extra_hosts:
       # - "ecc.api.com:172.0.0.1"
      ##dns:
        ##- 223.5.5.5
  php72:
    restart: always #设置自启动
    image: luwenbin8023/php:7.2.33-fpm-alpine3.12 #本地镜像
    volumes:
      - ../www:/data/www #站点根目录
      #- /php72/php.ini:/usr/local/etc/php/php.ini:ro
      - ./log/php:/opt/log/php #php log目录
      ##- ./dev.ini:/usr/local/etc/php/conf.d/safety.ini
    ports:
      - "9200:9000/tcp"
    container_name: php72
    privileged: true #设定读写权限
    stdin_open: true
    tty: true
  php74:
    restart: always #设置自启动
    image: luwenbin8023/php:7.4.12-fpm-alpine3.12 #本地镜像
    volumes:
      - ../www:/data/www #站点根目录
      #- /php74/php.ini:/usr/local/etc/php/php.ini:ro
      #- ./php:/opt/config #配置文件
      - ./log/php:/opt/log/php #php log目录
      #- ./dev.ini:/usr/local/etc/php/conf.d/safety.ini
    ports:
      - "9300:9000/tcp"
    container_name: php74
    privileged: true #设定读写权限
    stdin_open: true
    tty: true
  mysql56:
    restart: always #设置自启动
    image: mysql:5.6.51 #本地镜像
    ports:
      - "3308:3306" #“宿主机端口:容器端口” 容器的3306端口映射到宿主机的3308端口
    volumes:
      - ./data/mysql56:/var/lib/mysql #数据目录
      - ./mysql56/my.cnf:/etc/mysql/my.cnf  #配置文件
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    container_name: mysql56
    privileged: true #设定读写权限
  mysql57:
      restart: always #设置自启动
      image: mysql:5.7.32 #本地镜像
      ports:
        - "3307:3306" #“宿主机端口:容器端口” 容器的3306端口映射到宿主机的3308端口
      volumes:
        - ./data/mysql57:/var/lib/mysql #数据目录
        - ./mysql57/my.cnf:/etc/mysql/my.cnf  #配置文件
      environment:
        MYSQL_ROOT_PASSWORD: root123456
      container_name: mysql57
      privileged: true #设定读写权限
  redis:
      restart: always #设置自启动
      image: redis:6.0.9-alpine3.12 #本地镜像
      volumes:
        - ./data/redis:/data/ #redis持久存储目录
        - ./redis/redis.conf:/usr/local/etc/redis/redis.conf #配置文件
      ports:
        - "6379:6379"
      command: redis-server /usr/local/etc/redis/redis.conf #redis持久存储
      container_name: redis
      privileged: true #设定读写权限
